### ISSUE TITLE
K4 compatibility, database creation

### ISSUE THREAD

**Issue by grommasdietz** [arnoson/kirby-stats#14]
Hi Arno

I was searching for a reduced and privacy friendly way of handling statistics. Your plugin looks promising! Is it already working with Kirby 4?

While I would like to check that by myself, I don’t quite understand how to setup the database right. Neither the example folder nor the documentation is giving any hint. Maybe the database is excluded with `.gitignore` by accident? Or should it be created? Anyway, I appreciate any hints and your help.

Thanks in advance
Jakob

**Comment by arnoson** [comment]
Hi Jakob

I have a test page running with this plugin and Kirby 4.0.0 and everythings seems to work!

The database uses sqlite which is created automatically if it doesn't exist. You can configure the path where the sqlite file will be created [here](https://github.com/arnoson/kirby-stats/blob/main/index.php#L15). Also any tables are [created ](https://github.com/arnoson/kirby-stats/blob/main/lib/Counters.php#L34-L54) automatically.

I should definitely improve documentation. Right now everything is still in early stages, although the basic functionality is working. The biggest downside is the mediocre bot filtering. I'll be on parental leave the next months, but I plan to spend more time developing this plugin in 2024, as I also really need a privacy friendly self hosted analytics for kirby.

**Comment by grommasdietz** [comment]
Thanks for your fast response. The problem on my setup was, that it has a structure with separate public folder. We can pretty easy support this by using:
```php
'sqlite' => kirby()->root('site') . '/plugins/kirby-stats/stats.sqlite',
```
However, This only works when defined in index.php, not in the kirby config, so I’ll create a pull request.

**Comment by arnoson** [comment]
I also use it mainly in public folder setups, but didn't know about the `site` root! I always ended up putting the sqlite in the base folder in this case. Do you think the plugin folder is a good default path? When updating the plugin it might get removed, not sure how composer behaves exactly.

**Comment by arnoson** [comment]
If you wan't to use the kirby roots in the config you can also use the config's [ready](https://getkirby.com/docs/reference/system/options/ready) hook

**Comment by grommas** [comment]
Same thoughts! Maybe a logs folder inside site?
