### ISSUE TITLE
Rendering issues on panel area navigation

### ISSUE THREAD

**Issue by grommasdietz** [arnoson/kirby-stats#16]
There are two rendering issues on the panel area navigation:

1. The settings do not open after click
2. The interval navigation width is too small

Tested in Safari (17.2.1), Firefox (120.0.1) and Chrome (120.0.6099.129) on MacOS (13.6.3). I'll investigate further and try to find a fix the next days!

**Comment by arnoson** [comment]
Good catch! The settings option wasn't doing anything so I removed it. For now all settings can be done via plugin options. Can you explain what you mean by 2.?

**Comment by grommasdietz** [comment]
The texts get truncated:
<img width="311" alt="Bildschirmfoto 2023-12-29 um 19 38 04" src="https://github.com/arnoson/kirby-stats/assets/136818759/6c3e0e3c-05d5-4ef9-8510-3692e119f150">

**Comment by arnoson** [comment]
Ah weird! Doesn't happen on windows, maybe it is a Kirby bug

**Comment by grommasdietz** [comment]
Seems to be solved after updating to the latest dev-main branch!
