### ISSUE TITLE
Idea: Add config option to enable/disable statistics

### ISSUE THREAD

**Issue by grommasdietz** [arnoson/kirby-stats#19]
It would be nice to have a kirby config option to enable/disable statistics. This would easily avoid counts on development.

We could disable on local environments (e.g. `config.example.test.php`):

```php
'arnoson.kirby-stats' => [
  'enabled' => false,
],
```
And enable it on server (e.g. `config.example.tld.php`):

```php
'arnoson.kirby-stats' => [
  'enabled' => true,
],
```

**Comment by arnoson** [comment]
Sounds great! Do you wan't to create a PR? Otherwise I can look into this as soon as I find some time. I guess the best place for this check would be in the [handle](https://github.com/arnoson/kirby-stats/blob/main/lib/KirbyStats.php#L38) method where we also check for logged in users

**Comment by grommasdietz** [comment]
Created a pull request!
